### ISSUE TITLE
 could not open port 'COM2': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

### ISSUE THREAD

**Issue by qqaadir** [canozcivelek/adaptive-led-matrix-highbeams#1]
Dear @canozcivelek, 

Could you please help with the following error message. 

could not open port 'COM3': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

I  have installed all python libraries, when it comes to this line `ser  = serial.Serial('COM3', 9600, timeout = 0)`  it spits error.  I am trying to setup software part only.

**Comment by canozcivelek** [comment]
Hi, it looks like the code is looking for a serial connection which doesn't currently exist. That part of the code is to establish serial communication with Arduino. Comment out all the lines that look for a serial connection until you actually connect your Arduino to your PC.

Good luck!

**Comment by qqaadir** [comment]
@canozcivelek,  As suggested, I have commented that part of the code out and it works fine now. I do have to troubleshoot a lot for different packages install errors especially tensorflow object detection module.  I was wondering why do I have many false positives on my own dataset? Is this expected as pretrained model used here comes from another dataset? If yes, could you please suggest on how do I create my own trained file on my own dataset? 
Thanks very much for taking time to reply my query.

**Comment by canozcivelek** [comment]
Hi, glad the problem is solved. As stated in the readme section, the dataset and pretrained model is not on a production level so it is perfectly normal that it doesn’t work properly on your data. I suggest you to follow some instructions on creating your own custom object detection model for better results on your own set of examples.

**Comment by qqaadir** [comment]
@canozcivelek, Could you please refer me to such instructions/articles/papers/github pages, I have been looking for a while now. As a beginner, I am not sure where to start. Your page is quite relevant to my aims.  I also have night time driving data and would like to create my own object detection  model to turn beam light ON/OFF.  I appreciate your suggestions.

**Comment by canozcivelek** [comment]
Hi, as stated in the acknowledgements section, Chris’ tutorials are to the point, easy to follow. You can start there, good luck!

**Comment by qqaadir** [comment]
@canozcivelek Thank you very much.
