### ISSUE TITLE
Projector Lens link

### ISSUE THREAD

**Issue by BrutalCaeser** [canozcivelek/adaptive-led-matrix-highbeams#4]
I have the led strip and the arduino board but don't know which projector lens to buy. Kindly provide the link to buy or share the model that you used on this project!
Thank You

**Comment by adastec-can** [comment]
Hi, I have bought it ages ago and don't have any links for it. Just go with any projector lens. I bought it from a spare parts dealer and bought a used headlight projector.

**Comment by BrutalCaeser** [comment]
Oh okay alright, thanks for the input!
